// https://redux.js.org/usage/structuring-reducers/normalizing-state-shape
export default function mockWeatherForecastNormalized() {
  return {
    data: {
      dates: [
        '2021-04-17',
        '2021-04-18',
        '2021-04-19',
        '2021-04-20',
        '2021-04-21',
        '2021-04-22',
        '2021-04-23',
        '2021-04-24',
        '2021-04-25',
        '2021-04-26',
        '2021-04-27',
        '2021-04-28',
        '2021-04-29',
        '2021-04-30',
        '2021-05-01',
      ],
      locations: {
        byId: {
          seattle: {
            name: 'seattle',
            description: 'Seattle city',
            latitude: 47.606209,
            longitude: -122.332071,
            region: 'cities',
          },
          bonney_lake: {
            name: 'bonney_lake',
            description: 'Bonney Lake',
            latitude: 47.179774,
            longitude: -122.186741,
            region: 'cities',
          },
        },
        allIds: [
          'seattle',
          'bonney_lake',
        ],
      },
      regions: {
        byId: {
          cities: {
            name: 'cities',
            description: 'Cities',
            locations: [
              {
                name: 'seattle',
                description: 'Seattle city',
                latitude: 47.606209,
                longitude: -122.332071,
                region: 'cities',
              },
              {
                name: 'bonney_lake',
                description: 'Bonney Lake',
                latitude: 47.179774,
                longitude: -122.186741,
                region: 'cities',
              },
            ],
          },
        },
        allIds: [
          'cities',
        ],
      },
      forecasts: {
        byId: {
          seattle: [
            {
              datetime: '2021-04-17',
              datetimeEpoch: 1618642800,
              tempmax: 74.9,
              tempmin: 47.3,
              temp: 60.9,
              feelslikemax: 74.9,
              feelslikemin: 47.3,
              feelslike: 60.9,
              dew: 40.1,
              humidity: 51.5,
              precip: 0,
              precipprob: 0,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 9.2,
              windspeed: 6.9,
              winddir: 179.6,
              pressure: 1021.5,
              cloudcover: 1.8,
              visibility: 12.2,
              solarradiation: 383.1,
              solarenergy: 24.9,
              uvindex: 8,
              severerisk: 10,
              sunrise: '06:15:59',
              sunriseEpoch: 1618665359,
              sunset: '20:02:31',
              sunsetEpoch: 1618714951,
              moonphase: 0.12,
              conditions: 'Clear',
              description: 'Clear conditions throughout the day.',
              icon: 'clear-day',
              stations: [
                'KSEA',
                'KBFI',
                'KRNT',
              ],
              source: 'comb',
            },
            {
              datetime: '2021-04-18',
              datetimeEpoch: 1618729200,
              tempmax: 72.9,
              tempmin: 52.1,
              temp: 62.1,
              feelslikemax: 72.9,
              feelslikemin: 52.1,
              feelslike: 62.1,
              dew: 41.4,
              humidity: 54.8,
              precip: 0,
              precipprob: 0,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 9.2,
              windspeed: 6.9,
              winddir: 270.1,
              pressure: 1019.9,
              cloudcover: 14.3,
              visibility: 15,
              solarradiation: 278.5,
              solarenergy: 24.1,
              uvindex: 8,
              severerisk: 10,
              sunrise: '06:14:07',
              sunriseEpoch: 1618751647,
              sunset: '20:03:56',
              sunsetEpoch: 1618801436,
              moonphase: 0.16,
              conditions: 'Clear',
              description: 'Clear conditions throughout the day.',
              icon: 'clear-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-19',
              datetimeEpoch: 1618815600,
              tempmax: 70.1,
              tempmin: 52.1,
              temp: 60.4,
              feelslikemax: 70.1,
              feelslikemin: 52.1,
              feelslike: 60.4,
              dew: 39.9,
              humidity: 49.2,
              precip: 0,
              precipprob: 0,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 8.1,
              windspeed: 5.8,
              winddir: 137.4,
              pressure: 1020.8,
              cloudcover: 18.5,
              visibility: 15,
              solarradiation: 255.5,
              solarenergy: 22.1,
              uvindex: 8,
              severerisk: 10,
              sunrise: '06:12:17',
              sunriseEpoch: 1618837937,
              sunset: '20:05:21',
              sunsetEpoch: 1618887921,
              moonphase: 0.21,
              conditions: 'Clear',
              description: 'Clear conditions throughout the day.',
              icon: 'clear-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-20',
              datetimeEpoch: 1618902000,
              tempmax: 65.9,
              tempmin: 51,
              temp: 58.1,
              feelslikemax: 65.9,
              feelslikemin: 51,
              feelslike: 58.1,
              dew: 44.4,
              humidity: 58.3,
              precip: 0,
              precipprob: 19,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 9.2,
              windspeed: 6.9,
              winddir: 180.4,
              pressure: 1017.4,
              cloudcover: 33.2,
              visibility: 14.9,
              solarradiation: 90.9,
              solarenergy: 7.8,
              uvindex: 3,
              severerisk: 10,
              sunrise: '06:10:28',
              sunriseEpoch: 1618924228,
              sunset: '20:06:45',
              sunsetEpoch: 1618974405,
              moonphase: 0.26,
              conditions: 'Partially cloudy',
              description: 'Partly cloudy throughout the day.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-21',
              datetimeEpoch: 1618988400,
              tempmax: 65,
              tempmin: 49,
              temp: 56.7,
              feelslikemax: 65,
              feelslikemin: 48.2,
              feelslike: 56.6,
              dew: 43.2,
              humidity: 64.4,
              precip: 0,
              precipprob: 4.8,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 12.8,
              windspeed: 8.1,
              winddir: 192.5,
              pressure: 1016.3,
              cloudcover: 31.3,
              visibility: 14.8,
              solarradiation: 138.9,
              solarenergy: 11.9,
              uvindex: 5,
              severerisk: 10,
              sunrise: '06:08:39',
              sunriseEpoch: 1619010519,
              sunset: '20:08:10',
              sunsetEpoch: 1619060890,
              moonphase: 0.31,
              conditions: 'Partially cloudy',
              description: 'Partly cloudy throughout the day.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-22',
              datetimeEpoch: 1619074800,
              tempmax: 61.1,
              tempmin: 49,
              temp: 54.8,
              feelslikemax: 61.1,
              feelslikemin: 46.6,
              feelslike: 54.6,
              dew: 37.9,
              humidity: 67.5,
              precip: 0,
              precipprob: 47.5,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 12.8,
              windspeed: 8.1,
              winddir: 201.1,
              pressure: 1018,
              cloudcover: 55,
              visibility: 15,
              solarradiation: 132,
              solarenergy: 11.6,
              uvindex: 5,
              severerisk: 10,
              sunrise: '06:06:52',
              sunriseEpoch: 1619096812,
              sunset: '20:09:34',
              sunsetEpoch: 1619147374,
              moonphase: 0.36,
              conditions: 'Rain, Partially cloudy',
              description: 'Partly cloudy throughout the day with a chance of rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-23',
              datetimeEpoch: 1619161200,
              tempmax: 58.9,
              tempmin: 49,
              temp: 53.9,
              feelslikemax: 58.9,
              feelslikemin: 46.6,
              feelslike: 53.6,
              dew: 45.7,
              humidity: 75.2,
              precip: 0.03,
              precipprob: 85.6,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 13.9,
              windspeed: 6.9,
              winddir: 183.8,
              pressure: 1014.9,
              cloudcover: 80,
              visibility: 14.9,
              solarradiation: 62.8,
              solarenergy: 5.3,
              uvindex: 2,
              severerisk: 10,
              sunrise: '06:05:05',
              sunriseEpoch: 1619183105,
              sunset: '20:10:58',
              sunsetEpoch: 1619233858,
              moonphase: 0.41,
              conditions: 'Rain, Partially cloudy',
              description: 'Partly cloudy throughout the day with morning rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-24',
              datetimeEpoch: 1619247600,
              tempmax: 65.9,
              tempmin: 50.1,
              temp: 56.8,
              feelslikemax: 65.9,
              feelslikemin: 50.1,
              feelslike: 56.8,
              dew: 42.2,
              humidity: 61.4,
              precip: 0,
              precipprob: 76.1,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 27.1,
              windspeed: 9.6,
              winddir: 175.7,
              pressure: 1012.2,
              cloudcover: 100,
              visibility: 15,
              solarradiation: 128.5,
              solarenergy: 11.2,
              uvindex: 5,
              severerisk: 10,
              sunrise: '06:03:19',
              sunriseEpoch: 1619269399,
              sunset: '20:12:23',
              sunsetEpoch: 1619320343,
              moonphase: 0.45,
              conditions: 'Rain, Overcast',
              description: 'Cloudy skies throughout the day with a chance of rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-25',
              datetimeEpoch: 1619334000,
              tempmax: 56.4,
              tempmin: 48.8,
              temp: 53.2,
              feelslikemax: 56.4,
              feelslikemin: 46.7,
              feelslike: 52.8,
              dew: 44.4,
              humidity: 74.2,
              precip: 0.18,
              precipprob: 71.4,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 34,
              windspeed: 10.5,
              winddir: 177.4,
              pressure: 1009.5,
              cloudcover: 100,
              visibility: 14.1,
              solarradiation: 27,
              solarenergy: 2.3,
              uvindex: 1,
              severerisk: 10,
              sunrise: '06:01:35',
              sunriseEpoch: 1619355695,
              sunset: '20:13:47',
              sunsetEpoch: 1619406827,
              moonphase: 0.48,
              conditions: 'Rain, Overcast',
              description: 'Cloudy skies throughout the day with a chance of rain throughout the day.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-26',
              datetimeEpoch: 1619420400,
              tempmax: 56,
              tempmin: 46.3,
              temp: 51,
              feelslikemax: 56,
              feelslikemin: 42.5,
              feelslike: 49.2,
              dew: 43,
              humidity: 75.2,
              precip: 0.24,
              precipprob: 47.5,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 21.5,
              windspeed: 11.9,
              winddir: 202.3,
              pressure: 1012.9,
              cloudcover: 74.4,
              visibility: 13.4,
              solarradiation: 233.9,
              solarenergy: 20.1,
              uvindex: 7,
              severerisk: 10,
              sunrise: '05:59:51',
              sunriseEpoch: 1619441991,
              sunset: '20:15:11',
              sunsetEpoch: 1619493311,
              moonphase: 0.5,
              conditions: 'Rain, Partially cloudy',
              description: 'Partly cloudy throughout the day with rain in the morning and afternoon.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-27',
              datetimeEpoch: 1619506800,
              tempmax: 58.2,
              tempmin: 43.1,
              temp: 50.1,
              feelslikemax: 58.2,
              feelslikemin: 38.2,
              feelslike: 48.3,
              dew: 37.4,
              humidity: 63.4,
              precip: 0,
              precipprob: 42.9,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 23.7,
              windspeed: 8.5,
              winddir: 124.7,
              pressure: 1019,
              cloudcover: 82.5,
              visibility: 15,
              solarradiation: 118.5,
              solarenergy: 10.4,
              uvindex: 3,
              severerisk: 10,
              sunrise: '05:58:09',
              sunriseEpoch: 1619528289,
              sunset: '20:16:35',
              sunsetEpoch: 1619579795,
              moonphase: 0.5,
              conditions: 'Partially cloudy',
              description: 'Partly cloudy throughout the day.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-28',
              datetimeEpoch: 1619593200,
              tempmax: 50.8,
              tempmin: 46.8,
              temp: 48.7,
              feelslikemax: 50.8,
              feelslikemin: 45.1,
              feelslike: 47.3,
              dew: 43.7,
              humidity: 83.5,
              precip: 0.34,
              precipprob: 42.9,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 27.1,
              windspeed: 9.1,
              winddir: 86,
              pressure: 1007.6,
              cloudcover: 100,
              visibility: 12.7,
              solarradiation: 22.7,
              solarenergy: 1.9,
              uvindex: 1,
              severerisk: 10,
              sunrise: '05:56:28',
              sunriseEpoch: 1619614588,
              sunset: '20:17:58',
              sunsetEpoch: 1619666278,
              moonphase: 0.52,
              conditions: 'Overcast',
              description: 'Cloudy skies throughout the day.',
              icon: 'cloudy',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-29',
              datetimeEpoch: 1619679600,
              tempmax: 61.6,
              tempmin: 50.1,
              temp: 55.7,
              feelslikemax: 61.6,
              feelslikemin: 50.1,
              feelslike: 55.7,
              dew: 46.4,
              humidity: 71.8,
              precip: 0.26,
              precipprob: 28.6,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 38.5,
              windspeed: 14.3,
              winddir: 162.7,
              pressure: 1013.4,
              cloudcover: 89.1,
              visibility: 13.7,
              solarradiation: 223.4,
              solarenergy: 19,
              uvindex: 6,
              severerisk: 10,
              sunrise: '05:54:48',
              sunriseEpoch: 1619700888,
              sunset: '20:19:22',
              sunsetEpoch: 1619752762,
              moonphase: 0.54,
              conditions: 'Partially cloudy',
              description: 'Partly cloudy throughout the day.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-30',
              datetimeEpoch: 1619766000,
              tempmax: 59.6,
              tempmin: 50.8,
              temp: 53.8,
              feelslikemax: 59.6,
              feelslikemin: 50.8,
              feelslike: 53.8,
              dew: 50.9,
              humidity: 90.5,
              precip: 0.8,
              precipprob: 23.8,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 23.5,
              windspeed: 10.7,
              winddir: 164.5,
              pressure: 1009.9,
              cloudcover: 97.4,
              visibility: 8.9,
              solarradiation: 116.2,
              solarenergy: 10.1,
              uvindex: 4,
              severerisk: 10,
              sunrise: '05:53:10',
              sunriseEpoch: 1619787190,
              sunset: '20:20:45',
              sunsetEpoch: 1619839245,
              moonphase: 0.58,
              conditions: 'Overcast',
              description: 'Cloudy skies throughout the day.',
              icon: 'cloudy',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-05-01',
              datetimeEpoch: 1619852400,
              tempmax: 56.4,
              tempmin: 46.4,
              temp: 52,
              feelslikemax: 56.4,
              feelslikemin: 44.1,
              feelslike: 51.5,
              dew: 49.4,
              humidity: 90.9,
              precip: 0.67,
              precipprob: 28.6,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 23.3,
              windspeed: 11.9,
              winddir: 184.4,
              pressure: 1014.1,
              cloudcover: 55.1,
              visibility: 11.3,
              solarradiation: 137.8,
              solarenergy: 11.9,
              uvindex: 5,
              severerisk: 10,
              sunrise: '05:51:32',
              sunriseEpoch: 1619873492,
              sunset: '20:22:08',
              sunsetEpoch: 1619925728,
              moonphase: 0.63,
              conditions: 'Partially cloudy',
              description: 'Partly cloudy throughout the day.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
          ],
          bonney_lake: [
            {
              datetime: '2021-04-17',
              datetimeEpoch: 1618642800,
              tempmax: 76.9,
              tempmin: 45.7,
              temp: 60.7,
              feelslikemax: 76.9,
              feelslikemin: 45.7,
              feelslike: 60.7,
              dew: 38.5,
              humidity: 50.3,
              precip: 0,
              precipprob: 0,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 9.2,
              windspeed: 6.9,
              winddir: 184.1,
              pressure: 1021.5,
              cloudcover: 1.2,
              visibility: 12.2,
              solarradiation: 413.9,
              solarenergy: 26.9,
              uvindex: 9,
              severerisk: 10,
              sunrise: '06:16:09',
              sunriseEpoch: 1618665369,
              sunset: '20:01:10',
              sunsetEpoch: 1618714870,
              moonphase: 0.12,
              conditions: 'Clear',
              description: 'Clear conditions throughout the day.',
              icon: 'clear-day',
              stations: [
                'KTCM',
                'KGRF',
                'KTIW',
                'KSEA',
                'KBFI',
                'KRNT',
              ],
              source: 'comb',
            },
            {
              datetime: '2021-04-18',
              datetimeEpoch: 1618729200,
              tempmax: 76,
              tempmin: 49,
              temp: 61.7,
              feelslikemax: 76,
              feelslikemin: 48.2,
              feelslike: 61.6,
              dew: 40.1,
              humidity: 52.3,
              precip: 0,
              precipprob: 0,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 9.2,
              windspeed: 6.9,
              winddir: 246.7,
              pressure: 1019.8,
              cloudcover: 12.8,
              visibility: 15,
              solarradiation: 279,
              solarenergy: 24.1,
              uvindex: 8,
              severerisk: 10,
              sunrise: '06:14:20',
              sunriseEpoch: 1618751660,
              sunset: '20:02:33',
              sunsetEpoch: 1618801353,
              moonphase: 0.16,
              conditions: 'Clear',
              description: 'Clear conditions throughout the day.',
              icon: 'clear-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-19',
              datetimeEpoch: 1618815600,
              tempmax: 70.1,
              tempmin: 47.9,
              temp: 58.4,
              feelslikemax: 70.1,
              feelslikemin: 47,
              feelslike: 58.3,
              dew: 40.9,
              humidity: 51.5,
              precip: 0,
              precipprob: 4.8,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 8.1,
              windspeed: 5.8,
              winddir: 159.5,
              pressure: 1020.8,
              cloudcover: 16.4,
              visibility: 15,
              solarradiation: 233.8,
              solarenergy: 20,
              uvindex: 7,
              severerisk: 10,
              sunrise: '06:12:31',
              sunriseEpoch: 1618837951,
              sunset: '20:03:56',
              sunsetEpoch: 1618887836,
              moonphase: 0.21,
              conditions: 'Clear',
              description: 'Clear conditions throughout the day.',
              icon: 'clear-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-20',
              datetimeEpoch: 1618902000,
              tempmax: 65.9,
              tempmin: 45.9,
              temp: 55.7,
              feelslikemax: 65.9,
              feelslikemin: 45.9,
              feelslike: 55.6,
              dew: 46.3,
              humidity: 58.8,
              precip: 0.17,
              precipprob: 52.4,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 9.2,
              windspeed: 6.9,
              winddir: 206.2,
              pressure: 1017.4,
              cloudcover: 31.8,
              visibility: 13.7,
              solarradiation: 74.8,
              solarenergy: 6.6,
              uvindex: 3,
              severerisk: 10,
              sunrise: '06:10:43',
              sunriseEpoch: 1618924243,
              sunset: '20:05:19',
              sunsetEpoch: 1618974319,
              moonphase: 0.26,
              conditions: 'Rain, Partially cloudy',
              description: 'Partly cloudy throughout the day with rain in the morning and afternoon.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-21',
              datetimeEpoch: 1618988400,
              tempmax: 65,
              tempmin: 45,
              temp: 54.6,
              feelslikemax: 65,
              feelslikemin: 45,
              feelslike: 54.5,
              dew: 43.2,
              humidity: 66,
              precip: 0,
              precipprob: 9.5,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 11.4,
              windspeed: 8.1,
              winddir: 213,
              pressure: 1016.4,
              cloudcover: 32,
              visibility: 14.5,
              solarradiation: 138.7,
              solarenergy: 12.1,
              uvindex: 5,
              severerisk: 10,
              sunrise: '06:08:56',
              sunriseEpoch: 1619010536,
              sunset: '20:06:42',
              sunsetEpoch: 1619060802,
              moonphase: 0.31,
              conditions: 'Partially cloudy',
              description: 'Partly cloudy throughout the day.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-22',
              datetimeEpoch: 1619074800,
              tempmax: 61.1,
              tempmin: 44,
              temp: 52.7,
              feelslikemax: 61.1,
              feelslikemin: 42.5,
              feelslike: 52.2,
              dew: 39.3,
              humidity: 68.8,
              precip: 0,
              precipprob: 52.4,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 11.4,
              windspeed: 8.1,
              winddir: 221,
              pressure: 1018.2,
              cloudcover: 50.8,
              visibility: 15,
              solarradiation: 167.4,
              solarenergy: 14.6,
              uvindex: 6,
              severerisk: 10,
              sunrise: '06:07:10',
              sunriseEpoch: 1619096830,
              sunset: '20:08:05',
              sunsetEpoch: 1619147285,
              moonphase: 0.36,
              conditions: 'Rain, Partially cloudy',
              description: 'Partly cloudy throughout the day with a chance of rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-23',
              datetimeEpoch: 1619161200,
              tempmax: 60,
              tempmin: 45.9,
              temp: 53,
              feelslikemax: 60,
              feelslikemin: 44.7,
              feelslike: 52.6,
              dew: 46.1,
              humidity: 75.6,
              precip: 0,
              precipprob: 100,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 9.2,
              windspeed: 8.1,
              winddir: 190.9,
              pressure: 1015,
              cloudcover: 76.2,
              visibility: 15,
              solarradiation: 74.1,
              solarenergy: 6.4,
              uvindex: 2,
              severerisk: 10,
              sunrise: '06:05:25',
              sunriseEpoch: 1619183125,
              sunset: '20:09:28',
              sunsetEpoch: 1619233768,
              moonphase: 0.41,
              conditions: 'Rain, Partially cloudy',
              description: 'Partly cloudy throughout the day with rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-24',
              datetimeEpoch: 1619247600,
              tempmax: 64.8,
              tempmin: 49.2,
              temp: 56.2,
              feelslikemax: 64.8,
              feelslikemin: 49.2,
              feelslike: 56.2,
              dew: 42.7,
              humidity: 63.5,
              precip: 0,
              precipprob: 95.1,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 24.2,
              windspeed: 8.7,
              winddir: 189,
              pressure: 1012.2,
              cloudcover: 100,
              visibility: 15,
              solarradiation: 126.3,
              solarenergy: 10.9,
              uvindex: 4,
              severerisk: 10,
              sunrise: '06:03:41',
              sunriseEpoch: 1619269421,
              sunset: '20:10:51',
              sunsetEpoch: 1619320251,
              moonphase: 0.45,
              conditions: 'Rain, Overcast',
              description: 'Cloudy skies throughout the day with rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-25',
              datetimeEpoch: 1619334000,
              tempmax: 57.6,
              tempmin: 48.1,
              temp: 53.2,
              feelslikemax: 57.6,
              feelslikemin: 46.6,
              feelslike: 53,
              dew: 43.5,
              humidity: 72.5,
              precip: 0.21,
              precipprob: 85.6,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 31.5,
              windspeed: 12.8,
              winddir: 178.4,
              pressure: 1009.7,
              cloudcover: 100,
              visibility: 13.9,
              solarradiation: 21,
              solarenergy: 1.6,
              uvindex: 1,
              severerisk: 10,
              sunrise: '06:01:58',
              sunriseEpoch: 1619355718,
              sunset: '20:12:13',
              sunsetEpoch: 1619406733,
              moonphase: 0.48,
              conditions: 'Rain, Overcast',
              description: 'Cloudy skies throughout the day with a chance of rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-26',
              datetimeEpoch: 1619420400,
              tempmax: 55.5,
              tempmin: 44.8,
              temp: 49.9,
              feelslikemax: 55.5,
              feelslikemin: 40.2,
              feelslike: 47.7,
              dew: 44.6,
              humidity: 82.7,
              precip: 0.39,
              precipprob: 61.9,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 23,
              windspeed: 11.4,
              winddir: 208,
              pressure: 1013.5,
              cloudcover: 93.1,
              visibility: 11.9,
              solarradiation: 241.9,
              solarenergy: 20.8,
              uvindex: 8,
              severerisk: 10,
              sunrise: '06:00:16',
              sunriseEpoch: 1619442016,
              sunset: '20:13:36',
              sunsetEpoch: 1619493216,
              moonphase: 0.5,
              conditions: 'Rain, Overcast',
              description: 'Cloudy skies throughout the day with a chance of rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-27',
              datetimeEpoch: 1619506800,
              tempmax: 60.2,
              tempmin: 41.3,
              temp: 50.7,
              feelslikemax: 60.2,
              feelslikemin: 36.6,
              feelslike: 49.1,
              dew: 37.7,
              humidity: 63.9,
              precip: 0,
              precipprob: 52.4,
              precipcover: null,
              preciptype: null,
              snow: 0,
              snowdepth: 0,
              windgust: 23.9,
              windspeed: 8.4,
              winddir: 177.8,
              pressure: 1019.1,
              cloudcover: 80.7,
              visibility: 15,
              solarradiation: 177.1,
              solarenergy: 15.4,
              uvindex: 5,
              severerisk: 10,
              sunrise: '05:58:35',
              sunriseEpoch: 1619528315,
              sunset: '20:14:58',
              sunsetEpoch: 1619579698,
              moonphase: 0.5,
              conditions: 'Rain, Partially cloudy',
              description: 'Partly cloudy throughout the day with a chance of rain.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-28',
              datetimeEpoch: 1619593200,
              tempmax: 52.4,
              tempmin: 47.4,
              temp: 49.3,
              feelslikemax: 52.4,
              feelslikemin: 45.3,
              feelslike: 48.5,
              dew: 44.1,
              humidity: 83,
              precip: 0.37,
              precipprob: 52.4,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 18.4,
              windspeed: 6,
              winddir: 128.6,
              pressure: 1007.2,
              cloudcover: 99.9,
              visibility: 13.2,
              solarradiation: 34.9,
              solarenergy: 3.1,
              uvindex: 1,
              severerisk: 10,
              sunrise: '05:56:56',
              sunriseEpoch: 1619614616,
              sunset: '20:16:20',
              sunsetEpoch: 1619666180,
              moonphase: 0.52,
              conditions: 'Rain, Overcast',
              description: 'Cloudy skies throughout the day with rain in the morning and afternoon.',
              icon: 'rain',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-29',
              datetimeEpoch: 1619679600,
              tempmax: 63.8,
              tempmin: 49,
              temp: 55.8,
              feelslikemax: 63.8,
              feelslikemin: 45.7,
              feelslike: 55.4,
              dew: 46.4,
              humidity: 72.5,
              precip: 0.17,
              precipprob: 33.2,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 33.8,
              windspeed: 10.5,
              winddir: 159.1,
              pressure: 1013.6,
              cloudcover: 87.5,
              visibility: 13.1,
              solarradiation: 199.6,
              solarenergy: 17.1,
              uvindex: 6,
              severerisk: 10,
              sunrise: '05:55:17',
              sunriseEpoch: 1619700917,
              sunset: '20:17:42',
              sunsetEpoch: 1619752662,
              moonphase: 0.54,
              conditions: 'Partially cloudy',
              description: 'Partly cloudy throughout the day.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-04-30',
              datetimeEpoch: 1619766000,
              tempmax: 57.6,
              tempmin: 49.9,
              temp: 52.6,
              feelslikemax: 57.6,
              feelslikemin: 49.9,
              feelslike: 52.6,
              dew: 50.7,
              humidity: 93.5,
              precip: 0.84,
              precipprob: 38,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 22.1,
              windspeed: 10.3,
              winddir: 196.3,
              pressure: 1010,
              cloudcover: 93.4,
              visibility: 7.6,
              solarradiation: 69.4,
              solarenergy: 6.1,
              uvindex: 2,
              severerisk: 10,
              sunrise: '05:53:40',
              sunriseEpoch: 1619787220,
              sunset: '20:19:04',
              sunsetEpoch: 1619839144,
              moonphase: 0.58,
              conditions: 'Overcast',
              description: 'Cloudy skies throughout the day.',
              icon: 'cloudy',
              stations: null,
              source: 'fcst',
            },
            {
              datetime: '2021-05-01',
              datetimeEpoch: 1619852400,
              tempmax: 55.3,
              tempmin: 44.1,
              temp: 51.3,
              feelslikemax: 55.3,
              feelslikemin: 41.9,
              feelslike: 50.8,
              dew: 49.4,
              humidity: 93,
              precip: 0.75,
              precipprob: 33.2,
              precipcover: null,
              preciptype: [
                'rain',
              ],
              snow: 0,
              snowdepth: 0,
              windgust: 25.1,
              windspeed: 11,
              winddir: 190.3,
              pressure: 1014.4,
              cloudcover: 53.1,
              visibility: 8.7,
              solarradiation: 120,
              solarenergy: 10.4,
              uvindex: 4,
              severerisk: 10,
              sunrise: '05:52:04',
              sunriseEpoch: 1619873524,
              sunset: '20:20:25',
              sunsetEpoch: 1619925625,
              moonphase: 0.63,
              conditions: 'Partially cloudy',
              description: 'Clearing in the afternoon.',
              icon: 'partly-cloudy-day',
              stations: null,
              source: 'fcst',
            },
          ],
        },
      },
    },
  };
}
